// Generated by CoffeeScript 1.6.2
(function() {
  var days, today;

  days = {
    monday: 1,
    tuesday: 2,
    wednesday: 3,
    thursday: 4,
    friday: 5,
    saturday: 6,
    sunday: 7
  };

  if (yesterday === thursday) {
    today = friday;
    we.excited();
    we.have({
      ball: today
    });
  }

}).call(this);
